### DISCUSSION TITLE
Prune and Check having issues with rclone to Google Drive but backup works flawlessly

### DISCUSSION THREAD

**Discussion by sym0nd0** [djmaze/resticker#195] [Q&A] [answered]
Hi all,
I've just set this up and backup works perfectly but both prune and check show errors and I can't fogure out what I've done wrong.

Check error:
```Checking configured repository 'rclone:googledrive:docker_backup' ...
rclone: 2024/06/02 14:13:38 NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults
rclone: 2024/06/02 14:13:38 Failed to create file system for "googledrive:docker_backup": didn't find section in config file
Fatal: unable to open repository at rclone:googledrive:docker_backup: error talking HTTP to rclone: exit status 1
Could not access the configured repository.
Not trying to initialize because SKIP_INIT is set in your configuration..
Scheduling check job according to cron expression.
new cron: 0 15 5 * * *
```
Prune error:
```Checking configured repository 'rclone:googledrive:docker_backup' ...
rclone: 2024/06/02 14:13:37 NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults
rclone: 2024/06/02 14:13:37 Failed to create file system for "googledrive:docker_backup": didn't find section in config file
Fatal: unable to open repository at rclone:googledrive:docker_backup: error talking HTTP to rclone: exit status 1
Could not access the configured repository.
Not trying to initialize because SKIP_INIT is set in your configuration..
Executing prune job on startup ...
Starting prune at 2024-06-02 14:13:37
rclone: 2024/06/02 14:13:37 NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults
rclone: 2024/06/02 14:13:37 Failed to create file system for "googledrive:docker_backup": didn't find section in config file
Fatal: unable to open repository at rclone:googledrive:docker_backup: error talking HTTP to rclone: exit status 1
Scheduling prune job according to cron expression.
new cron: 0 0 4 * * *
```
Backup being fine and working as expected:
```
Checking configured repository 'rclone:googledrive:docker_backup' ...
Repository found.
Executing backup on startup ...
Starting Backup at 2024-06-02 14:13:44
open repository
lock repository
using parent snapshot 8662d1a1
load index files
start scan on [/mnt/volumes]
start backup on [/mnt/volumes]
scan finished in 6.902s: 169313 files, 11.624 GiB
Files:          84 new,   411 changed, 168818 unmodified
Dirs:            7 new,   107 changed,  6038 unmodified
Data Blobs:    517 new
Tree Blobs:    114 new
Added to the repository: 136.574 MiB (26.279 MiB stored)
processed 169313 files, 11.624 GiB in 0:20
snapshot 34d57041 saved
Backup successful
Forget about old snapshots based on RESTIC_FORGET_ARGS = --keep-last 10 --keep-daily 7 --keep-weekly 5 --keep-monthly 12
Applying Policy: keep 10 latest, 7 daily, 5 weekly, 12 monthly snapshots
keep 2 snapshots:
ID        Time                 Host        Tags            Reasons           Paths
-----------------------------------------------------------------------------------------
8662d1a1  2024-06-02 12:19:36  docker      docker-volumes  last snapshot     /mnt/volumes
                                                           daily snapshot
                                                           weekly snapshot
                                                           monthly snapshot
34d57041  2024-06-02 14:13:44  docker      docker-volumes  last snapshot     /mnt/volumes
                                                           daily snapshot
                                                           weekly snapshot
                                                           monthly snapshot
-----------------------------------------------------------------------------------------
2 snapshots
Finished backup at 2024-06-02 14:14:16 after 32 seconds
Scheduling backup job according to cron expression.
new cron: 0 30 3 * * *
```
Docker Compose used for this:
```
services:
  backup:
    image: mazzolino/restic
    hostname: docker
    container_name: restic_backup
    restart: unless-stopped
    env_file:
      - .env
    environment:
      RUN_ON_STARTUP: "true"
      BACKUP_CRON: "0 30 3 * * *"
      RESTIC_REPOSITORY: rclone:googledrive:docker_backup
      RESTIC_PASSWORD: $RESTIC_PASSWORD
      RESTIC_BACKUP_SOURCES: /mnt/volumes
      RESTIC_BACKUP_ARGS: >-
        --tag docker-volumes
        --verbose
      RESTIC_FORGET_ARGS: >-
        --keep-last 10
        --keep-daily 7
        --keep-weekly 5
        --keep-monthly 12
      TZ: $TZ
    volumes:
      - ~/docker-compose:/mnt/volumes:ro
      - ~/.config/rclone:/root/.config/rclone

  prune:
    image: mazzolino/restic
    hostname: docker
    container_name: restic_prune
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SKIP_INIT: "true"
      RUN_ON_STARTUP: "true"
      PRUNE_CRON: "0 0 4 * * *"
      RESTIC_REPOSITORY: rclone:googledrive:docker_backup
      RESTIC_PASSWORD: $RESTIC_PASSWORD
      TZ: $TZ

  check:
    image: mazzolino/restic
    hostname: docker
    container_name: restic_check
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SKIP_INIT: "true"
      RUN_ON_STARTUP: "false"
      CHECK_CRON: "0 15 5 * * *"
      RESTIC_CHECK_ARGS: >-
        --read-data-subset=10%
      RESTIC_REPOSITORY: rclone:googledrive:docker_backup
      RESTIC_PASSWORD: $RESTIC_PASSWORD
      TZ: $TZ
```
Nothing special in the .env, just the password for Restic and Europe/London for TZ, so I'll not include that.

Redated rclone.conf, again nothing special but just in case I've messed that up:
```
[googledrive]
type = drive
client_id = <redacted>
client_secret = <redacted?
scope = drive
token = {<redacted>}
team_drive =
```
rclone.conf location
```
rclone config file
Configuration file is stored at:
/home/simon/.config/rclone/rclone.conf
```
I tried to update the volume in the compose file to `      - ~/.config/rclone:/home/simon/.config/rclone` instead of `      - ~/.config/rclone:/root/.config/rclone` and that just broke backup too... 🤦🏼‍♂️

System info:
```
screenfetch
                          ./+o+-       simon@newbuntu
                  yyyyy- -yyyyyy+      OS: Ubuntu 22.04 jammy
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 5.15.0-107-generic
           .++ .:/++++++/-.+sss/`      Uptime: 19h 39m
         .:++o:  /++++++++/:--:/-      Packages: 1109
        o:+o+:++.`..```.-/oo+++++/     Shell: bash 5.1.16
       .:+o:+o/.          `+sssoo+/    Resolution: 1536x864
  .++/+:+oo+o:`             /sssooo.   WM: OpenBox
 /+++//+:`oo+o               /::--:.   GTK Theme: Adwaita [GTK3]
 \+/+o+++`o++o               ++////.   Disk: 2.0T / 5.4T (38%)
  .++.o+++oo+:`             /dddhhh.   CPU: Intel Core i7-7700K @ 8x 4.5GHz [43.0°C]
       .+.o+oo:.          `oddhhhh+    GPU: Quadro P400
        \+.++o+o``-````.:ohdhhhhh+     RAM: 6570MiB / 15860MiB
         `:o+++ `ohhhhhhhhyo++os:
           .o:`.syhhhhhhh/.oo++o`
               /osyyyyyyo++ooo+++/
                   ````` +oo+++o\:
                          `oo++.
```
Anyone able to explain where I've gone wrong please?

Thanks
