### DISCUSSION TITLE
--exclude argument not working?

### DISCUSSION THREAD

**Discussion by dolf-s** [djmaze/resticker#81] [Q&A] [answered]
Hi all,
I'm trying to exclude a bunch of .mp4 files from a backup. No matter what I try, I can't get these files to be excluded from the backup.

I'm using docker compose and below is a snippet from my compose file. I've also tried including the full path ('/source/shinobi/**/*.mp4') and tried using an exclude file, but nothing seems to force the exclusion of the mp4 files from ending up in the backup. I was hoping that the --verbose flag would shed more light on what commands are actually passed to the container but unfortunately it's not visible in the logs.

Am I doing something wrong perhaps?

`           RESTIC_BACKUP_ARGS: >-
            --tag shinobi 
            --exclude='*.mp4' 
            --verbose`

**Comment by djmaze** [comment]
@dolf-s It looks like everything is on one line here. Then the `>-` is not needed and may do harm. Other than that, it looks correct.

**Comment by dolf-s** [comment]
It looks that way, but it's the way the copy-paste turned out. I tried it on one line first, without the `>-` like this:
`RESTIC_BACKUP_ARGS: --tag shinobi --exclude='*.mp4' --verbose`

Later I tried it as per your compose example yml:
`RESTIC_BACKUP_ARGS: >- 
   --tag shinobi
   --exclude='*.mp4'
   --verbose`

**Reply by dolf-s** [reply]
hmm - can't get a line feed in the second code snippet, but I guess you understand what i mean... :-)

**Reply by djmaze** [reply]
Hmm. Maybe you have an older version of the image which did not yet support `RESTIC_BACKUP_ARGS`. Did you pull the latest image or do you use at least the 1.2.0 release?

**Reply by ThomDietrich** [reply]
What does not work exactly? When you run the image you should see the command as it is executed. Does it look correct to you?

Maybe to help you, here is one of my working configs:

```yaml
environment:
     ...
      RESTIC_BACKUP_ARGS: >-
        --tag resticker
        --verbose
      RESTIC_FORGET_ARGS: --keep-last 3 --keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly 3
      TZ: Europe/Berlin
```

Your yaml has to be correct. Your second isn't and the different characters in your first might create issues. What do you see when you execute `docker-compose config`?

**Reply by dolf-s** [reply]
Below is the result of `docker-compose config`. What fails is that the backups include mp4 files, which I want to exclude from the backup. The 'tag' and 'verbose' arguments seem to be passed correctly. One thing that struck me is that the mp4 files show as executable files from the command line. I guess it is irrelevant for the --exclude argument, but just mentioning it just in case.

```
 resticker:
    container_name: resticker-shinobi
    environment:
      B2_ACCOUNT_ID: ****************
      B2_ACCOUNT_KEY: ***************
      BACKUP_CRON: 0 20 2 * * *
      POST_COMMANDS_EXIT: docker start shinobi
      PRE_COMMANDS: docker stop shinobi
      RESTIC_BACKUP_ARGS: --tag shinobi  --exclude='*.mp4'  --verbose
      RESTIC_BACKUP_SOURCES: /source/shinobi
      RESTIC_FORGET_ARGS: --tag shinobi --keep-last 10 --keep-daily 1
      RESTIC_PASSWORD: ***************
      RESTIC_REPOSITORY: ***************
      RUN_ON_STARTUP: "true"
      TZ: Europe/Amsterdam
    hostname: home-server
    image: mazzolino/restic
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:rw
    - /home/dolf/docker/shared/resticker:/var/log:rw
    - /home/dolf/docker/shinobi:/source/shinobi:ro
```
