### ISSUE TITLE
Zombie processes left

### ISSUE THREAD

**Issue by LucaTNT** [djmaze/resticker#105]
Hi,
thanks for the great tool.

I've been noticing an issue (always have, actually): zombie processes are left on my server after running the backup task.

```USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      1956  0.0  0.0      0     0 ?        Z    Oct08   0:00 [prune] <defunct>
root      4806  0.0  0.0      0     0 ?        Z    Oct08   0:00 [backup] <defunct>
root      5551  0.0  0.0      0     0 ?        Z    03:00   0:00 [backup] <defunct>
root      6819  0.0  0.0      0     0 ?        Z    Oct07   0:00 [backup] <defunct>
luca     10578  0.0  0.0   6072   892 pts/5    S+   10:21   0:00 grep Z
root     12110  0.0  0.0      0     0 ?        Z    Oct06   0:00 [backup] <defunct>
root     18567  0.0  0.0      0     0 ?        Z    Oct08   0:00 [backup] <defunct>
```

My docker compose looks like this (s3 is actually a minio-backed instance):

```
  backup_config:
    image: mazzolino/restic
    hostname: docker
    restart: always
    environment:
      BACKUP_CRON: "0 0 3 * * *"
      RESTIC_REPOSITORY: s3:...
      RESTIC_PASSWORD: ...
      RESTIC_BACKUP_SOURCES: /mnt/config
      RESTIC_BACKUP_ARGS: >-
        --tag docker-config
        --exclude='*.tmp'
        --verbose
      RESTIC_FORGET_ARGS: >-
        --keep-last 10
        --keep-daily 7
        --keep-weekly 5
        --keep-monthly 12
      AWS_ACCESS_KEY_ID: ...
      AWS_SECRET_ACCESS_KEY: ...
      TZ: Europe/Rome
      PRE_COMMANDS: /usr/bin/curl -fsS -m 10 --retry 5 -o /dev/null https://...
      POST_COMMANDS_SUCCESS: /usr/bin/curl -fsS -m 10 --retry 5 -o /dev/null https://...
      POST_COMMANDS_FAILURE: /usr/bin/curl -fsS -m 10 --retry 5 -o /dev/null https://...
    volumes:
      - /home/luca/docker-proxmox:/mnt/config:ro

  prune:
    image: mazzolino/restic
    hostname: docker
    restart: always
    environment:

      PRUNE_CRON: "0 0 4 * * *"
      RESTIC_REPOSITORY: s3:...
      RESTIC_PASSWORD: ...
      AWS_ACCESS_KEY_ID: ...
      AWS_SECRET_ACCESS_KEY: ...
      RESTIC_FORGET_ARGS: >-
        --keep-last 10
        --keep-daily 7
        --keep-weekly 5
        --keep-monthly 12
      TZ: Europe/Rome
      PRE_COMMANDS: /usr/bin/curl -fsS -m 10 --retry 5 -o /dev/null https://...
      POST_COMMANDS_SUCCESS: /usr/bin/curl -fsS -m 10 --retry 5 -o /dev/null https://...
      POST_COMMANDS_FAILURE: /usr/bin/curl -fsS -m 10 --retry 5 -o /dev/null https://...
```

Any ideas?

Thanks!
