### ISSUE TITLE
RESTIC_REPOSITORY_FILE cannot be used

### ISSUE THREAD

**Issue by nonsavant** [djmaze/resticker#112]
Setting a value for  RESTIC_REPOSITORY_FILE is ignored and overwritten by the default value of  RESTIC_REPOSITORY, rendering the RESTIC_REPOSITORY_FILE environment variable unusable.

Sample docker-compose file snippet:

```
  restic:
    image: mazzolino/restic
    container_name: restic
    secrets:
      - restic_repository
      - restic_password
    environment:
      BACKUP_CRON: "0 30 3 * * *"
      RESTIC_REPOSITORY_FILE: /run/secrets/restic_repository
      RESTIC_PASSWORD_FILE: /run/secrets/restic_password
      RESTIC_BACKUP_ARGS: "--verbose=2"
      RUN_ON_STARTUP: "true"
    volumes:
       - /data/media:/data
```
  
Result of `docker inspect`:

```
$ docker inspect restic | grep RESTIC_REPO
                "RESTIC_REPOSITORY_FILE=/run/secrets/restic_repository",
                "RESTIC_REPOSITORY=/mnt/restic"
```

I guess the fix is something like: If RESTIC_REPOSITORY_FILE is provided, don't set  RESTIC_REPOSITORY with the default value.
