### ISSUE TITLE
Issue with restic backup sources 

### ISSUE THREAD

**Issue by farzadha2** [djmaze/resticker#150]
Hi
I was wondering if someone else had this issue before, Currently trying to backup 2 folder but in the logs only backing up 1 folder 

This is part of my docker compose

```
services:
  sftp_backup:
    image: mazzolino/restic
    restart: always
    hostname: sftp-backup
    privileged: true
    environment:
      RUN_ON_STARTUP: "true"
      POST_COMMANDS_FAILURE: |-
        curl -X POST --data "{\"title\": \"Backup failed\", \"body\": \"\"}" http://notify:5000
      BACKUP_CRON: "0 30 23 * * *"
      RESTIC_REPOSITORY: sftp:root@192.168.7.253:/media/usb/docker3
      RESTIC_PASSWORD: mypassword
      RESTIC_BACKUP_SOURCES: /scsi1
      RESTIC_BACKUP_SOURCES: /scsi2
      RESTIC_BACKUP_ARGS: >-
        --tag backupsftp
        --verbose
      RESTIC_FORGET_ARGS: >-
        --keep-last 90
      TZ: America/Bogota
    volumes:
      - /scsi1:/scsi1
      - /scsi2:/scsi2
      - /root/.ssh/:/root/.ssh/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - notification

```

```
sftp_backup_1  | Forget about old snapshots based on RESTIC_FORGET_ARGS = --keep-last 90
sftp_backup_1  | Applying Policy: keep 90 latest snapshots
sftp_backup_1  | keep 1 snapshots:
sftp_backup_1  | ID        Time                 Host         Tags        Reasons        Paths
sftp_backup_1  | -----------------------------------------------------------------------------
sftp_backup_1  | 5a1570d2  2022-10-09 18:21:22  sftp-backup  backupsftp  last snapshot  /scsi2
sftp_backup_1  | -----------------------------------------------------------------------------
sftp_backup_1  | 1 snapshots
sftp_backup_1  | 
sftp_backup_1  | Finished backup at 2022-10-09 18:23:55 after 153 seconds
```
