### ISSUE TITLE
Errors backing up with Docker Swarm

### ISSUE THREAD

**Issue by ericvoshall** [djmaze/resticker#153]
Hi, I just set this up in a Swarm of 4 nodes and I am getting errors when a backup job takes place using (mostly) the example Swarm compose file. All 4 nodes are trying to backup to the same repository at the same time, leading to a whole bunch of issues with repository locks.

It makes sense that there would be lock conflicts with each task trying to backup to the same restic repository, but I don't see how this would work in a Swarm at all with locks in place.

Here's my compose file:

```yaml
---
version: "3.9"

services:
  backup:
    image: mazzolino/restic:1.6.0
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    environment:
      B2_ACCOUNT_ID: $B2_ACCOUNT_ID
      B2_ACCOUNT_KEY: $B2_ACCOUNT_KEY
      BACKUP_CRON: "0 0 3 * * *"
      RESTIC_BACKUP_ARGS: >-
        --exclude='backingFsBlockDev'
        --exclude='*.tmp'
        --verbose
      RESTIC_BACKUP_SOURCES: /data
      RESTIC_FORGET_ARGS: >-
        --keep-within-daily 7d
        --keep-within-weekly 1m
      RESTIC_PASSWORD: $RESTIC_PASSWORD
      RESTIC_REPOSITORY: b2:my-bucket:/docker
      RUN_ON_STARTUP: "true"
      TZ: America/New_York
    hostname: "{{.Node.ID}}"
    volumes:
      - /var/lib/docker/volumes:/data/volumes:ro
      - /mnt/docker:/data/nas

  prune:
    image: mazzolino/restic:1.6.0
    deploy:
      mode: replicated
      placement:
        constraints: [node.labels.short_hostname != rpi]
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - backup
    environment:
      B2_ACCOUNT_ID: $B2_ACCOUNT_ID
      B2_ACCOUNT_KEY: $B2_ACCOUNT_KEY
      PRUNE_CRON: "0 0 4 * * *"
      RESTIC_PASSWORD: $RESTIC_PASSWORD
      RESTIC_REPOSITORY: b2:my-bucket:/docker
      TZ: America/New_York
    hostname: docker

  check:
    image: mazzolino/restic:1.6.0
    deploy:
      mode: replicated
      placement:
        constraints: [node.labels.short_hostname != rpi]
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - backup
    environment:
      B2_ACCOUNT_ID: $B2_ACCOUNT_ID
      B2_ACCOUNT_KEY: $B2_ACCOUNT_KEY
      CHECK_CRON: "0 30 4 * * *"
      RESTIC_CHECK_ARGS: >-
        --read-data-subset=10%
      RESTIC_PASSWORD: $RESTIC_PASSWORD
      RESTIC_REPOSITORY: b2:my-bucket:/docker
      TZ: America/New_York
    hostname: docker
```
