### ISSUE TITLE
exclude-file AND files-from

### ISSUE THREAD

**Issue by Enissay** [djmaze/resticker#164]
Hi all,

I was trying to take advantage of the `PRE_COMMANDS` var to provide a list of files to skip but the syntax doesnt seem to bbe working... I have tried many ways and still failed... 
Of course using something like `exclude_file_ok.txt` (see below)  works but is very unredable... Please advise what am I missing ?

```yaml
...
    environment:

      RESTIC_BACKUP_ARGS: --verbose --exclude-file /mnt/restic_config/exclude_file.txt --tag resticker-auto

      PRE_COMMANDS: |-
        mkdir -p /mnt/restic_config
        
        echo -e ".git/\n.config/\nbin/\nobj/" > /mnt/restic_config/exclude_file_ok.txt
                      
        cat <<- EOF > /mnt/restic_config/exclude_file.txt
          .config/
          .git/
          bin/
          obj/
        EOF
```

Next, I would like also to provide a list of files/folders from a file to be loaded using restic's `--files-from`, but I don't see such option for `resticker`, or have I missed it ?
In any case, such file will be crated the same way as for the exclusion list, so It would also benefit the solution for the above issue... 

Thank you

**Comment by Enissay** [comment]
As workaround I managed to do it like this:
- For Q1:
It is not as optimized as the above but it achieves what's needed: easily readable + ability to add comments
```yaml
      PRE_COMMANDS: |-
        mkdir -p /mnt/restic_config

        # Exclude file        
        echo "# Generals"         >> /mnt/restic_config/exclude_file.txt
        echo ".config/"           >> /mnt/restic_config/exclude_file.txt
        echo ".git/"              >> /mnt/restic_config/exclude_file.txt
        echo "..."                >> /mnt/restic_config/exclude_file.txt
```

- For Q2:
For `RESTIC_BACKUP_SOURCES`, the project does not seem to support reading files to BU from a text file. It seems to simply parse the given values as string split up by spaces. So no way to add comments or try to make it nicely readable
```yaml
      RESTIC_BACKUP_SOURCES: >-
        # Category 1
        /mnt/path11
        /mnt/path12
        # Category 2
        /mnt/path21
        /mnt/path22
        # Category 3
        /mnt/path31
        #...
```

I am not sure if anyone have better ideas for the above ?

**Comment by djmaze** [comment]
Sorry for the late answer. For Q1, you could just create your exclude file locally and then mount it into the container, like this:

```yaml
services:
  backup:
    environment:
      RESTIC_BACKUP_ARGS: --verbose --exclude-file /mnt/restic_config/exclude_file.txt --tag resticker-auto
    configs:
      source: exclude_file.txt
      target: /mnt/restic_config/exclude_file.txt
  # ...

configs:
   exclude_file.txt:
     file: exclude_file.txt
```
