### ISSUE TITLE
Feature Request: Support for docker secrets

### ISSUE THREAD

**Issue by Natanel-Shitrit** [djmaze/resticker#177]
## How?
Like `mysql` environment variable `MYSQL_PASSWORD_FILE`, an equivalent `RESTIC_PASSWORD_FILE`.

## Example Usage
```yaml
version: "3.3"

services:
  backup:
    image: mazzolino/restic
    hostname: docker
    restart: unless-stopped
    environment:
      # ...
      RESTIC_PASSWORD_FILE: /run/secrets/restic_password
      # ...
    secrets:
      - restic_password
secrets:
  restic_password:
    file: ./RESTIC_PWD
```
