### ISSUE TITLE
No valid operating mode configured! Exiting.

### ISSUE THREAD

**Issue by ALEX8642** [djmaze/resticker#180]
When running this docker compose file, I get the following repeating over and over:
```
appdata-restic-backup-1  | No valid operating mode configured! Exiting.
appdata-restic-backup-1  | Checking configured repository '/mnt/restic' ...
appdata-restic-backup-1  | Repository found.
```
The docker events call - docker daemon shows fatal error code 1 (repeating):
```2024-01-21T19:19:33.804089963Z container die 1bd7160aac27f3d484a206aaf9901b552b8898ad0072f414f2c7eab00aac3922 (com.docker.compose.config-hash=7021956cb1867c24e682529d063ed8938c5b58415a6c263f279b27f36317648b, com.docker.compose.container-number=1, com.docker.compose.depends_on=, com.docker.compose.image=sha256:0804a5e5c3d422cbabcb4432bed6d77422c1addf7360eaae7b4e70171fad95f2, com.docker.compose.oneoff=False, com.docker.compose.project=appdata, com.docker.compose.project.config_files=/home/alex8642/appdata/docker-compose.yml, com.docker.compose.project.working_dir=/home/alex8642/appdata, com.docker.compose.service=restic-backup, com.docker.compose.version=2.21.0, execDuration=0, exitCode=1, image=mazzolino/restic, name=appdata-restic-backup-1)
```
Docker compose file:
```yaml restic-backup:
    image: mazzolino/restic
    hostname: restic-backup
    restart: unless-stopped
    command:
      -  backup
      -  /mnt/backup
    environment:
      - RUN_ON_STARTUP=true
      # Run once every month on the 30th day
      - BACKUP_CRON=0 30 3 * * *
      - RESTIC_REPOSITORY=s3:http://192.168.50.32:9000/test-restic-backup
      - RESTIC_PASSWORD=*********
      - RESTIC_BACKUP_SOURCES=/mnt/backup
    # RESTIC_BACKUP_ARGS: >-
    # --tag backup-tag
    # --exclude='folder/to/exclude'
    # --exclude='somefile.txt'
    # Keep docs: https://restic.readthedocs.io/en/stable/060_forget.html
      - RESTIC_FORGET_ARGS= >-
         --keep-daily 7
         --keep-weekly 5
         --keep-monthly 12
         --keep-yearly 3
         --keep-tag 'keep'
     #AWS_ACCESS_KEY_ID:
     #AWS_SECRET_ACCESS_KEY:
      - TZ=Etc/UTC
    volumes:
      - ~/alex8642/ItbLab:/mnt/backup:ro
      - ./restic:/mnt/backup:rw

  restic-prune:
    image: mazzolino/restic
    hostname: restic-prune
    restart: unless-stopped
    environment:
      - RUN_ON_STARTUP=true
 # Run once every month on the 30th day
      - PRUNE_CRON=0 30 3 * * *
      - RESTIC_REPOSITORY=s3:http://192.168.50.32:9000/test-restic-backup
      - RESTIC_PASSWORD=*********
     #AWS_ACCESS_KEY_ID:
     #AWS_SECRET_ACCESS_KEY:
      - TZ=Etc/UTC

  restic-check:
    image: mazzolino/restic
    hostname: restic-check
    restart: unless-stopped
    environment:
      - RUN_ON_STARTUP=true
     # Run once every month on the 30th day
      - PRUNE_CRON=0 30 3 * * *
      - RESTIC_CHECK_ARGS= >-
         --read-data-subset=10%
      - RESTIC_REPOSITORY=s3:http://192.168.50.32:9000/test-restic-backup
      - RESTIC_PASSWORD=*********
     #AWS_ACCESS_KEY_ID:
     #AWS_SECRET_ACCESS_KEY:
      - TZ=Etc/UTC

    minio:
    image: ghcr.io/imagegenius/minio
    hostname: minio
    restart: unless-stopped
    ports:
      - 9001:9001 # web ui
      - 9000:9000 # api port
    environment:
      - MINIO_ROOT_USER=alex8642
      - MINIO_ROOT_PASSWORD=********* # must be longer than 8
      - PUID=99
      - PGID=100
      - UMASK=022
    volumes:
      - ./minio:/config # bucket storage```

**Comment by ALEX8642** [comment]
> @ALEX8642 You have a `command` configured, that is wrong. Resticker is completely configured via env variables.

Ok. Incidentally enough though, that was an attempt to solve the issue. I did not have commands previously and it had zero impact on the error. I have confirmed once again. Updating original issue post to remove command section. What is an ENG?

**Comment by escoand** [comment]
Look at the line with `minio`. There seems to be a incorrect indentation.

**Comment by ALEX8642** [comment]
> Look at the line with `minio`. There seems to be a incorrect indentation.

@escoand MinIO is working fine (GUI is fully accessible), so I don't think that's the issue.

**Comment by escoand** [comment]
You deployed it exactly like you copy-pasted? Hard to believe it is working with this config. So we could just guess what's the real problem.

**Comment by escoand** [comment]
I'm also quite sure this is also not working as intended:
```yaml
   - RESTIC_FORGET_ARGS= >-
       ...
```

I suppose it was copied/converted from something like this:
```yaml
    RESTIC_FORGET_ARGS: >=
      ...
```

Or use it like this:
```yaml
   - >-
      RESTIC_FORGET_ARGS=
      ...
```

**Comment by ALEX8642** [comment]
> I'm also quite sure this is also not working as intended:
> 
> ```yaml
>    - RESTIC_FORGET_ARGS= >-
>        ...
> ```
> 
> I suppose it was copied/converted from something like this:
> 
> ```yaml
>     RESTIC_FORGET_ARGS: >=
>       ...
> ```
> 
> Or use it like this:
> 
> ```yaml
>    - >-
>       RESTIC_FORGET_ARGS=
>       ...
> ```

I will change the syntax as you have indicated when I am able tonight and let you know. Appreciate the feedback. As mentioned though, minIO and all my other containers seem to be working OK. It's only Restic backup that gives me that error and goes into a restart loop.

**Comment by djmaze** [comment]
Also there is something missing at the beginning. I would expect something like this:

```yaml
services:
  restic-backup:
    image: mazzolino/restic
    # ...
```

Let's shorten this discussion, here is your config with (hopefully) all the indentation errors fixed:

```yaml
services:
  restic-backup:
    image: mazzolino/restic
    hostname: restic-backup
    restart: unless-stopped
    environment:
      - RUN_ON_STARTUP=true
      # Run once every month on the 30th day
      - BACKUP_CRON=0 30 3 * * *
      - RESTIC_REPOSITORY=s3:http://minio:9000/test-restic-backup
      - RESTIC_PASSWORD=*********
      - RESTIC_BACKUP_SOURCES=/mnt/backup
      # RESTIC_BACKUP_ARGS: >-
      # --tag backup-tag
      # --exclude='folder/to/exclude'
      # --exclude='somefile.txt'
      # Keep docs: https://restic.readthedocs.io/en/stable/060_forget.html
      - RESTIC_FORGET_ARGS= >-
         --keep-daily 7
         --keep-weekly 5
         --keep-monthly 12
         --keep-yearly 3
         --keep-tag 'keep'
      #AWS_ACCESS_KEY_ID:
      #AWS_SECRET_ACCESS_KEY:
      - TZ=Etc/UTC
    volumes:
      - ~/alex8642/ItbLab:/mnt/backup:ro
      - ./restic:/mnt/backup:rw

  restic-prune:
    image: mazzolino/restic
    hostname: restic-prune
    restart: unless-stopped
    environment:
      - RUN_ON_STARTUP=true
      # Run once every month on the 30th day
      - PRUNE_CRON=0 30 3 * * *
      - RESTIC_REPOSITORY=s3:http://minio:9000/test-restic-backup
      - RESTIC_PASSWORD=*********
      #AWS_ACCESS_KEY_ID:
      #AWS_SECRET_ACCESS_KEY:
      - TZ=Etc/UTC

  restic-check:
    image: mazzolino/restic
    hostname: restic-check
    restart: unless-stopped
    environment:
      - RUN_ON_STARTUP=true
      # Run once every month on the 30th day
      - PRUNE_CRON=0 30 3 * * *
      - RESTIC_CHECK_ARGS= >-
         --read-data-subset=10%
      - RESTIC_REPOSITORY=s3:http://minio:9000/test-restic-backup
      - RESTIC_PASSWORD=*********
      #AWS_ACCESS_KEY_ID:
      #AWS_SECRET_ACCESS_KEY:
      - TZ=Etc/UTC

  minio:
    image: ghcr.io/imagegenius/minio
    hostname: minio
    restart: unless-stopped
    ports:
      - 9001:9001 # web ui
      - 9000:9000 # api port
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=********* # must be longer than 8
      - PUID=99
      - PGID=100
      - UMASK=022
    volumes:
      - ./minio:/config # bucket storage   
```

**Comment by ALEX8642** [comment]
Hi. The changes made per @djmaze and @escoand had no effect. Error persists.

**Comment by escoand** [comment]
We need the actual used yaml. Currently it's just guesswork.

**Comment by ALEX8642** [comment]
As a side note, they are other containers running in this all working great. I only pasted the section for restic. This is why the services title was not present in previous versions. That was always present. usernames and passwords removed for obvious reasons.
```
---
version: "2.1"
services:
  restic-backup:
    image: mazzolino/restic
    hostname: restic-backup
    restart: unless-stopped
    environment:
      - RUN_ON_STARTUP=true
      # Run once every month on the 30th day
      - BACKUP_CRON=0 30 3 * * *
      - RESTIC_REPOSITORY=s3:http://minio:9000/test-restic-backup
      - RESTIC_PASSWORD=
      - RESTIC_BACKUP_SOURCES=/mnt/backup
      # RESTIC_BACKUP_ARGS: >-
      # --tag backup-tag
      # --exclude='folder/to/exclude'
      # --exclude='somefile.txt'
      # Keep docs: https://restic.readthedocs.io/en/stable/060_forget.html
      - >-
         RESTIC_FORGET_ARGS=
         --keep-daily 7
         --keep-weekly 5
         --keep-monthly 12
         --keep-yearly 3
         --keep-tag 'keep'
      #AWS_ACCESS_KEY_ID:
      #AWS_SECRET_ACCESS_KEY:
      - TZ=Etc/UTC
    volumes:
      - ~/alex8642/ItbLab:/mnt/backup:ro
      - ./restic:/mnt/backup:rw

  restic-prune:
    image: mazzolino/restic
    hostname: restic-prune
    restart: unless-stopped
    environment:
      - RUN_ON_STARTUP=true
      # Run once every month on the 30th day
      - PRUNE_CRON=0 30 3 * * *
      - RESTIC_REPOSITORY=s3:http://minio:9000/test-restic-backup
      - RESTIC_PASSWORD=
      #AWS_ACCESS_KEY_ID:
      #AWS_SECRET_ACCESS_KEY:
      - TZ=Etc/UTC

  restic-check:
    image: mazzolino/restic
    hostname: restic-check
    restart: unless-stopped
    environment:
      - RUN_ON_STARTUP=true
      # Run once every month on the 30th day
      - PRUNE_CRON=0 30 3 * * *
      - >-
        RESTIC_CHECK_ARGS=
         --read-data-subset=10%
      - RESTIC_REPOSITORY=s3:http://minio:9000/test-restic-backup
      - RESTIC_PASSWORD=
      #AWS_ACCESS_KEY_ID:
      #AWS_SECRET_ACCESS_KEY:
      - TZ=Etc/UTC

  minio:
    image: ghcr.io/imagegenius/minio
    hostname: minio
    restart: unless-stopped
    ports:
      - 9001:9001 # web ui
      - 9000:9000 # api port
    environment:
      - MINIO_ROOT_USER=
      - MINIO_ROOT_PASSWORD= # must be longer than 8
      - PUID=99
      - PGID=100
      - UMASK=022
    volumes:
      - ./minio:/config # bucket storage
```
