### ISSUE TITLE
open: s3.getCredentials: no credentials found. Use `-o s3.unsafe-anonymous-auth=true` for anonymous authentication

### ISSUE THREAD

**Issue by nprime496** [djmaze/resticker#218]
Hi,

Thank you for the repo. It should fit my needs well.

However, I can't get to make it work.

I edited the `docker-compose.example.yml` with my config but I get the error : 

```
Fatal: create repository at s3:s3.eu-central-003.backblazeb2.com/bucket failed: Fatal: unable to open repository at s3:s3.eu-central-003.backblazeb2.com/bucket: open: s3.getCredentials: no credentials found. Use `-o s3.unsafe-anonymous-auth=true` for anonymous authentication
```
Here is the minimal docker docker compose file to reproduce the issue:

```yml
version: "3.3"

services:
  backup:
    image: mazzolino/restic
    hostname: docker
    restart: unless-stopped
    environment:
      RUN_ON_STARTUP: "true"
      BACKUP_CRON: "0 30 3 * * *"
      RESTIC_REPOSITORY: s3:s3.eu-central-003.backblazeb2.com/bucket
      RESTIC_PASSWORD: supersecret
      RESTIC_BACKUP_SOURCES: /mnt/volumes
      RESTIC_BACKUP_ARGS: >-
        --tag docker-volumes
        --exclude some-folder/cache
        --exclude another-folder/with\ space
        --exclude *.tmp
        --verbose
      RESTIC_FORGET_ARGS: >-
        --keep-last 10
        --keep-daily 7
        --keep-weekly 5
        --keep-monthly 12
      B2_ACCOUNT_ID: xxxxxxx
      B2_ACCOUNT_KEY: yyyyyyyy
      TZ: Europe/Berlin
    volumes:
      - /var/lib/docker/volumes:/mnt/volumes:ro

  prune:
    image: mazzolino/restic
    hostname: docker
    restart: unless-stopped
    environment:
      SKIP_INIT: "true"
      RUN_ON_STARTUP: "true"
      PRUNE_CRON: "0 0 4 * * *"
      RESTIC_REPOSITORY: b2:my-repo:/restic
      RESTIC_PASSWORD: supersecret
      B2_ACCOUNT_ID: xxxxxxx
      B2_ACCOUNT_KEY: yyyyyyyy
      TZ: Europe/Berlin

  check:
    image: mazzolino/restic
    hostname: docker
    restart: unless-stopped
    environment:
      SKIP_INIT: "true"
      RUN_ON_STARTUP: "false"
      CHECK_CRON: "0 15 5 * * *"
      RESTIC_CHECK_ARGS: >-
        --read-data-subset=10%
      RESTIC_REPOSITORY: b2:my-repo:/restic
      RESTIC_PASSWORD: supersecret
      B2_ACCOUNT_ID: xxxxxxx
      B2_ACCOUNT_KEY: yyyyyyyy
      TZ: Europe/Berlin
```

What is strange is that if the repo didn't exist or if the credentials were wrong I should have a different error but no, it says that I have no credentials.

It is [suggested that the error comes from missing variables](https://forum.restic.net/t/getcredentials-error/8408) like `RESTIC_PASSWORD`  however I did configure them. 

I even checked using `docker exec -it resticker-backup-1 env | grep RESTIC` and the credentials are there and populated correctly.

I really don't understand. Can you help me ?
