### ISSUE TITLE
backup multiple dirs

### ISSUE THREAD

**Issue by mapa0402** [djmaze/resticker#27]
Hi, I have a lot of containers not under the same root volume unfortunately, would it be possible to mount multiple volume-sources to backup with this tool?

**Comment by smainz** [comment]
I do not understand your question exactly. Here is an example of how I use this container to back up multiple volumes in a docker-compose file:


```
  restic-backup:
    image: mazzolino/restic
    container_name: restic-gitea-backup
    hostname: gitea-backup
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
    environment:
      BACKUP_CRON: "0 0 1 ? * * *"
      RESTIC_REPOSITORY: /mnt/restic
      RESTIC_PASSWORD: restic
      RESTIC_BACKUP_SOURCES: /backup/gitea
      RESTIC_BACKUP_TAGS: gitea-backup,automated
      RESTIC_FORGET_ARGS: --prune --keep-last 14 --keep-daily 1 --tag gitea-backup,automated --keep-tag keep
      TZ: Europe/Berlin
      PRE_COMMANDS: |-
        docker stop gitea-app gitea-db
      POST_COMMANDS_SUCCESS: |-
        echo backup successful
      POST_COMMANDS_FAILURE: |-
        echo backup failed
      POST_COMMANDS_EXIT: |-
        docker start gitea-app gitea-db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - db_data://backup/gitea/db_data
      - gitea_data:/backup/gitea/gitea_data
      - /var/restic-repository/gitea:/mnt/restic
```

This will backup the volumes
- db_data and
- gitea_data

into a restic repository on the host at `/var/restic-repository/gitea`. The only thing is it can be a bit of typing if you want to restore just one of the volumes, but this will not be the case for my setup.
