### ISSUE TITLE
May we have an mailx in the official container?

### ISSUE THREAD

**Issue by smainz** [djmaze/resticker#29]
Hello,

I´d like to send a mail after in the POST_COMMAND. Could you include a simple mailx inside the container. Something like https://pkgs.alpinelinux.org/package/edge/community/x86/heirloom-mailx?

Thanks

**Comment by djmaze** [comment]
I prefer the microservice approach of having a separate service for notifications. Personally, I am using an [apprise-microservice](https://github.com/djmaze/apprise-microservice) container like this:

```yaml
services:              
  app:       
    image: mazzolino/restic:1.1
    environment:
      # ...
      POST_COMMANDS_FAILURE: |-
        curl -X POST --data "{\"title\": \"Backup failed\", \"body\": \"\"}" http://notify:5000
    networks:
      - notification

  notify:
    image: mazzolino/apprise-microservice:0.1
    environment:
      NOTIFICATION_URLS: mailto://...
    networks:
      - notification

networks:
  notification:
```

If there is interest in this approach, I can add this example to the README.
