### ISSUE TITLE
To check whether Cron job ran? PRE, POST, EXIT are executed?

### ISSUE THREAD

**Issue by Altiano** [djmaze/resticker#34]
How do I check whether the cron job ran?
or to know whether any of the commands in PRE, POST and EXIT environment variable,
are executed?

**Comment by djmaze** [comment]
As I said in #32, for the PRE- and POST-commands every line is printed and then executed. You should thus be able to see each command before it is run.

Same goes for the backup. It should say `Starting Backup at ...` before starting each backup.

**Comment by Altiano** [comment]
Printed where,
I mean the container has cron job right?
And when the cron job ran, which I guess will execute the PRE, POST commands and also the actual backup,
but where these logs got printed? a file?

I got issue that my backup not running as expected.
```
 environment:
          BACKUP_CRON: "0 0 2 * * *"
          RESTIC_REPOSITORY: **
          RESTIC_PASSWORD: **
          RESTIC_BACKUP_SOURCES: /volumes
          RESTIC_FORGET_ARGS: --keep-daily 7 --keep-weekly 4
```

It should run at 2 AM right?

But after checking the snapshots, no new ones presented
