### ISSUE TITLE
Restic seems to not exclude my dir

### ISSUE THREAD

**Issue by e-belair** [djmaze/resticker#54]
I'm using a nfs share as volume for storing the repository, so I need to exclude this volume path from restic backup. When I include the path in RESTIC_BACKUP_ARGS, restic seems to still backup the whole directory:

```
version: "3.3"

services:
  app:
    image: mazzolino/restic
    hostname: docker
    restart: "always"
    container_name: resticker
    environment:
      BACKUP_CRON: "0 30 2 * * *"
      RESTIC_REPOSITORY: /mnt/restic
      RESTIC_PASSWORD: supersecret
      #RESTIC_BACKUP_SOURCES: /data
      #RESTIC_BACKUP_TAGS: docker-volumes
      # Exclu le volume backup ovh
      RESTIC_BACKUP_ARGS: --exclude='/data/volumes/resticker_ovh-backup/'
      RESTIC_FORGET_ARGS: --prune --keep-last 14 --keep-daily 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts:/scripts:ro
      - ./msmtprc:/etc/msmtprc:ro

      # Backup ovh
      - type: volume
        source: ovh-backup
        target: /mnt/restic
        volume:
          nocopy: true

      # data dirs
      - /home/databases:/data/databases
      - /home/docker/volumes:/data/volumes:ro
      - /home/www:/data/www:ro
      - /home/svn:/data/svn:ro
      - /etc:/data/etc:ro
      - /root:/data/root:ro
    labels:
      - "traefik.enable=false"

volumes:
  ovh-backup:
    driver: local # Must be set to avoid issues.
    driver_opts:
      type: "nfs"
      o: "addr=xxxxxxxxxxxxxxxxxxxxx,nolock,soft,rw"
      device: ":/xxxxxxxxxx/restic"
```

EDIT:
I've edited the file backup to echo the command line:
```
set +e
echo "restic backup ${RESTIC_BACKUP_ARGS:-} ${tag_options} ${RESTIC_BACKUP_SOURCES}"
restic backup ${RESTIC_BACKUP_ARGS:-} ${tag_options} ${RESTIC_BACKUP_SOURCES}
if [ $? -ne 0 ]
then
	set -e
	run_commands "${POST_COMMANDS_FAILURE:-}"
	exit
else
	set -e
fi
```
And the command output:
```
Starting Backup at 2020-10-04 12:26:07
restic backup --exclude='/data/volumes/resticker_ovh-backup/'  /data
repository cadce6ce opened successfully, password is correct
```
But while the backup is running, I can see the directory being backed up:
```
$ dc exec app backup
Starting Backup at 2020-10-04 12:33:13
restic backup --exclude='/data/volumes/resticker_ovh-backup/'  /data
repository cadce6ce opened successfully, password is correct
[0:40] 102260 files 35.913 GiB, total 108219 files 64.659 GiB, 0 errors
/data/volumes/resticker_ovh-backup/_data/data/00/006720c5f4ef7a98ac47dbb4fd7e0f09b1ab88d11a2fe7c1a6652b715b111f67
/data/volumes/resticker_ovh-backup/_data/data/00/00684f918c3daea649b15efdc98ec93d7b6a5638a0c827478006aa2877683263
```
So I'm getting an extremely big backup that includes himself ^^"
