### ISSUE TITLE
Best way to backup docker volumes

### ISSUE THREAD

**Issue by kgnfth** [djmaze/resticker#56]
As i am to restic since yesterday
For now i am using it like this

```yaml
version: "3.3"

services:
  backup:
    image: mazzolino/restic
    hostname: docker
    environment:
      RUN_ON_STARTUP: "true"
      BACKUP_CRON: "0 0 1 ? * * *"
      RESTIC_REPOSITORY: b2:dockervolumes:/
      RESTIC_PASSWORD: "${RESTIC_PASSWORD}"
      RESTIC_BACKUP_SOURCES: /mnt/volumes
      RESTIC_BACKUP_ARGS: >-
        --tag docker-volumes
        --exclude='*.tmp'
        --verbose
      RESTIC_FORGET_ARGS: >-
        --keep-last 3
        --keep-daily 7
      B2_ACCOUNT_ID: "${RESTIC_B2_ACCOUNT_ID}"
      B2_ACCOUNT_KEY: "${RESTIC_B2_ACCOUNT_KEY}"
      TZ: Europe/Berlin
    volumes:
      # peertube
      - /var/lib/docker/volumes/captain--peertube-db-data:/mnt/volumes/captain--peertube-db-data
      - /var/lib/docker/volumes/captain--peertube-redis-data:/mnt/volumes/captain--peertube-redis-data
      - /var/lib/docker/volumes/captain--peertube-peertube-data:/mnt/volumes/captain--peertube-peertube-data
      - /var/lib/docker/volumes/captain--peertube-peertube-config:/mnt/volumes/captain--peertube-peertube-config
      # Lychee
      - /var/lib/docker/volumes/captain--photos-conf:/mnt/volumes/captain--photos-conf
      - /var/lib/docker/volumes/captain--photos-db-data:/mnt/volumes/captain--photos-db-data
      - /var/lib/docker/volumes/captain--photos-sym:/mnt/volumes/captain--photos-sym
      - /var/lib/docker/volumes/captain--photos-uploads:/mnt/volumes/captain--photos-uploads
  prune:
    image: mazzolino/restic
    hostname: docker
    environment:
      RUN_ON_STARTUP: "true"
      PRUNE_CRON: "0 0 4 * * *"
      RESTIC_REPOSITORY: b2:dockervolumes:/restic
      RESTIC_PASSWORD: "${RESTIC_PASSWORD}"
      B2_ACCOUNT_ID: "${RESTIC_B2_ACCOUNT_ID}"
      B2_ACCOUNT_KEY: "${RESTIC_B2_ACCOUNT_KEY}"
      TZ: Europe/Berlin
```

So all the backups goes like this
/mnt/volumes/captain--*

![image](https://user-images.githubusercontent.com/73314940/97778426-5ff6cc80-1b77-11eb-8fef-e6360acc4b1c.png)

should i change the backup source to `/var/lib/docker/` or is `/mnt/volumes/` fine ?
