### ISSUE TITLE
Issues when using a SFTP repository

### ISSUE THREAD

**Issue by drskullster** [djmaze/resticker#65]
Hi there,

I have some issues when I try to use this image with a SFTP repository by mounting a volume in `/root/.ssh` with a config file and a private key.

First issue is that I have to disable the `StrictHostKeyChecking` option in my config to bypass the prompt for key fingerprint verification, otherwise the script will fail at init.

Second issue is that I couldn't find any way to change the permissions or owner on the mounted volume, so I have to run docker-compose as root (ssh will fail if owner of config file is different than the user running the command). Also, this is not an issue for me but I believe it will fail on windows because the files are mounted with 777 permissions, and ssh won't allow that on the private key.

Is there a better way to run the image with a restic SFTP repository ?

---

`docker-compose.yml`:

```
...
    volumes:
      - ./data:/data:ro
      - ./ssh_config:/root/.ssh
```

`ssh_config/config`: 
```
host *
  StrictHostKeyChecking no
```

And of course my private key in `ssh_config/id_rsa`.

**Comment by zoispag** [comment]
I am not using restic with sftp, but have you tried to mount the `.ssh` folder as read-only with `:ro` flag?

```yml
    volumes:
      - ./ssh_config:/root/.ssh:ro
```

**Comment by drskullster** [comment]
I tried, but docker needs write permissions in the folder for the `known_hosts` file.

**Comment by djmaze** [comment]
@drskullster Concerning the host key problem, you can just mount a `known_hosts` file containing the correct host key into the container.

Concerning the private key, you can chown to root and chmod 0600 it locally before mounting.

I am not doing this myself because I am using swarm mode which makes this much easier:

```yaml
services:
  backup:
    # ...
    configs:
      - source: known_hosts
        target: /root/.ssh/known_hosts
        uid: '0'
        gid: '0'
        mode: 0600
    secrets:
      - source: backup_rsa
        target: /root/.ssh/id_rsa
        uid: '0'
        gid: '0'
        mode: 0600
```

(I heartly recommend using swarm mode even when running on a single host only.)
