### ISSUE TITLE
support swarm secrets

### ISSUE THREAD

**Issue by NeuerUser** [djmaze/resticker#78]
If I see that correctly, initialization fails if one wants to use the "--password-file" option. It is possible to add it to RESTIC_BACKUP_ARGS, but this is not used in the entrypoint.sh:
`if restic cat config > /dev/null; then
  echo "Repository found."
else
  echo "Could not access the configured repository. Trying to initialize (in case it has not been initialized yet) ..."
  if restic init; then
    echo "Repository successfully initialized."
  else
    if [ "${SKIP_INIT_CHECK:-}" == "true" ]; then
      echo "Initialization failed. Ignoring errors because SKIP_INIT_CHECK is set in your configuration."
    else
      echo "Initialization failed. Please see error messages above and check your configuration. Exiting."
      exit 1
    fi
  fi
fi
echo -e "\n"
`
Could you add the usage of the RESTIC_BACKUP_ARGS for these two calls? Or is there a better solution to use docker secrets?

**Comment by djmaze** [comment]
@NeuerUser There is `RESTIC_PASSWORD_FILE` which I am using in my own swarm setups:

```
RESTIC_PASSWORD_FILE: /run/secrets/restic_password
```

**Comment by NeuerUser** [comment]
Hey, that's perfect. Haven't found it in the docs, but it is exactly what is needed. Thanks!

**Comment by djmaze** [comment]
I already thought about adding more examples. Would probably make sense.

**Comment by ahgraber** [comment]
Would you add support for other (arbitrary) secrets using the `_FILE` identifier?  
My use case -- If I have databases that I want to back up, it would be useful to be able to pass Restic the DB info as secrets, and then refer to the environmental variable in  the custom PRE_COMMAND.

example:
```yml
services:
  backup:
    ...
    secrets:
      - DB_USER
      - DB_PWD
      - DB_NAME
    environment:
        ...
        DB_USER_FILE: /run/secrets/DB_USER
        DB_PWD_FILE: /run/secrets/DB_PWD  
        DB_NAME_FILE: /run/secrets/DB_NAME
        PRE_COMMANDS: |-
          docker exec -i mariadb-container mysqldump -u"$DB_USER" -p"$DB_PWD" --databases "$DB_NAME" > /mnt/restic/dump.sql
    ...
```


Here's a script that looks for `_FILE` in all environmental variables and reads in from `/run/secrets`.  You'd have to copy the script into the image in the Dockerfile and then call the script from `entrypoint`.

```sh
  
#!/bin/sh

# logic cribbed from linuxserver.io: 
# https://github.com/linuxserver/docker-baseimage-ubuntu/blob/bionic/root/etc/cont-init.d/01-envfile

# iterate over environmental variables
# if variable ends in "_FILE"
for FULLVAR in $(env | grep "^.*_FILE="); do
    # trim "=..." from variable name
    VARNAME=$(echo $FULLVAR | sed "s/=.*//g")
    echo "[secret-init] Evaluating ${VARNAME} ..."

    # set SECRETFILE to the contents of the variable
    # Use 'eval hack' for indirect expansion in sh: https://unix.stackexchange.com/questions/111618/indirect-variable-expansion-in-posix-as-done-in-bash
    # WARNING: It's not foolproof is an arbitrary command injection vulnerability 
    eval SECRETFILE="\$${VARNAME}"

    echo "[secret-init] Setting SECRETFILE to ${SECRETFILE}"  # DEBUG - rm for prod!
    
    # if SECRETFILE exists
    if [[ -f ${SECRETFILE} ]]; then
        # strip the appended "__FILE" from environmental variable name
        STRIPVAR=$(echo $VARNAME | sed "s/__FILE//g")
        echo "[secret-init] Set STRIPVAR to ${STRIPVAR}"  # DEBUG - rm for prod!

        # set value to contents of secretfile
        eval ${STRIPVAR}=$(cat "${SECRETFILE}")
        echo "[secret_init] Set ${STRIPVAR} to $(eval echo \$${STRIPVAR})"  # DEBUG - rm for prod!
        
        export "${STRIPVAR}"
        echo "[secret-init] Success! ${STRIPVAR} set from ${VARNAME}"
        
    else
        echo "[secret-init] ERROR: Cannot find secret in ${VARNAME}"
    fi
done
```

**Comment by djmaze** [comment]
@ahgraber Hmm.. This looks like a big pile of special-case code which might not be needed. Did you try this?

```yaml
services:
  backup:
    ...
    secrets:
      - DB_USER
      - DB_PWD
      - DB_NAME
    environment:
        ...
        PRE_COMMANDS: |-
          docker exec -i mariadb-container mysqldump -u"$(cat /run/secrets/DB_USER)" -p"$(cat /run/secrets/DB_PWD)" --databases "$(cat /run/secrets/DB_NAME)" > /mnt/restic/dump.sql
    ...
```
