### ISSUE TITLE
Several hosts for only one repository

### ISSUE THREAD

**Issue by tdehaeze** [djmaze/resticker#95]
Hi, 
I am using resticker for almost a year and I am loving it.
However, recently I discovered when runing `docker exec restic restic snapshots` that my snapshots are spread over several "hosts".

Here are the output of  the command:
```
Applying Policy: keep 7 daily, 4 weekly, 12 monthly snapshots
keep 11 snapshots:
ID        Time                 Host          Tags        Reasons           Paths
----------------------------------------------------------------------------------
da47f506  2021-05-23 00:30:00  2e2af1be088a              weekly snapshot   /source
5458ebfa  2021-05-30 00:30:00  2e2af1be088a              weekly snapshot   /source
a4664b7a  2021-05-31 00:30:18  2e2af1be088a              monthly snapshot  /source
20a3d641  2021-06-06 00:30:30  2e2af1be088a              weekly snapshot   /source
8f86c5e9  2021-06-07 00:30:19  2e2af1be088a              daily snapshot    /source
f3e93cf7  2021-06-08 00:30:30  2e2af1be088a              daily snapshot    /source
17cff6bd  2021-06-09 00:30:30  2e2af1be088a              daily snapshot    /source
f2eebbe4  2021-06-10 00:30:30  2e2af1be088a              daily snapshot    /source
f9b25cfb  2021-06-11 00:30:30  2e2af1be088a              daily snapshot    /source
ddaeda45  2021-06-12 00:30:30  2e2af1be088a              daily snapshot    /source
d2e0b369  2021-06-13 00:30:30  2e2af1be088a              daily snapshot    /source
                                                         weekly snapshot
                                                         monthly snapshot
----------------------------------------------------------------------------------
11 snapshots

keep 1 snapshots:
ID        Time                 Host          Tags        Reasons           Paths
----------------------------------------------------------------------------------
0506c8de  2021-04-18 00:30:00  c448c639d0b5              daily snapshot    /source
                                                         weekly snapshot
                                                         monthly snapshot
----------------------------------------------------------------------------------
1 snapshots

keep 5 snapshots:
ID        Time                 Host          Tags        Reasons           Paths
----------------------------------------------------------------------------------
385725eb  2021-04-13 00:30:00  6bf5499157b0              daily snapshot    /source
4a4a0d48  2021-04-14 00:30:00  6bf5499157b0              daily snapshot    /source
3346e919  2021-04-15 00:30:00  6bf5499157b0              daily snapshot    /source
7d0fcefc  2021-04-16 00:30:00  6bf5499157b0              daily snapshot    /source
38c11301  2021-04-17 00:30:00  6bf5499157b0              daily snapshot    /source
                                                         weekly snapshot
                                                         monthly snapshot
----------------------------------------------------------------------------------
5 snapshots

keep 9 snapshots:
ID        Time                 Host          Tags        Reasons           Paths
----------------------------------------------------------------------------------
bdf6100e  2021-02-21 00:30:00  eb3614586f55              weekly snapshot   /source
52b1051f  2021-02-28 00:30:00  eb3614586f55              weekly snapshot   /source
                                                         monthly snapshot
3281697b  2021-03-04 00:30:00  eb3614586f55              daily snapshot    /source
6ff56fbc  2021-03-05 00:30:00  eb3614586f55              daily snapshot    /source
4b7b2e2b  2021-03-06 00:30:00  eb3614586f55              daily snapshot    /source
8bbb88e0  2021-03-07 00:30:00  eb3614586f55              daily snapshot    /source
                                                         weekly snapshot
92b01248  2021-03-08 00:30:00  eb3614586f55              daily snapshot    /source
58f57702  2021-03-09 00:30:00  eb3614586f55              daily snapshot    /source
47493db3  2021-03-10 00:30:00  eb3614586f55              daily snapshot    /source
                                                         weekly snapshot
                                                         monthly snapshot
----------------------------------------------------------------------------------
9 snapshots

keep 2 snapshots:
ID        Time                 Host          Tags        Reasons           Paths
----------------------------------------------------------------------------------
fc3128b9  2021-04-11 00:30:00  f7492c4481da              daily snapshot    /source
                                                         weekly snapshot
ec4f3609  2021-04-12 00:30:00  f7492c4481da              daily snapshot    /source
                                                         weekly snapshot
                                                         monthly snapshot
----------------------------------------------------------------------------------
2 snapshots

keep 10 snapshots:
ID        Time                 Host          Tags        Reasons           Paths
----------------------------------------------------------------------------------
9313c80f  2021-06-30 00:30:31  2f4af964b1d8              monthly snapshot  /source
44da09dc  2021-07-11 00:30:31  2f4af964b1d8              weekly snapshot   /source
00e83424  2021-07-18 00:30:30  2f4af964b1d8              weekly snapshot   /source
b7b8ab24  2021-07-22 00:30:29  2f4af964b1d8              daily snapshot    /source
15001eaa  2021-07-23 00:30:30  2f4af964b1d8              daily snapshot    /source
463cbdcc  2021-07-24 00:30:22  2f4af964b1d8              daily snapshot    /source
c7c8c59c  2021-07-25 00:30:31  2f4af964b1d8              daily snapshot    /source
                                                         weekly snapshot
695554a3  2021-07-26 00:30:31  2f4af964b1d8              daily snapshot    /source
9018b43a  2021-07-27 00:30:31  2f4af964b1d8              daily snapshot    /source
820c651d  2021-07-28 00:30:30  2f4af964b1d8              daily snapshot    /source
                                                         weekly snapshot
                                                         monthly snapshot
----------------------------------------------------------------------------------
10 snapshots

keep 9 snapshots:
ID        Time                 Host          Tags        Reasons           Paths
----------------------------------------------------------------------------------
d3204257  2021-03-28 00:30:00  4fe0fd3f2130              weekly snapshot   /source
3beee8d0  2021-03-31 00:30:00  4fe0fd3f2130              monthly snapshot  /source
c066a254  2021-04-04 00:30:00  4fe0fd3f2130              daily snapshot    /source
                                                         weekly snapshot
a1506420  2021-04-05 00:30:00  4fe0fd3f2130              daily snapshot    /source
baaf657a  2021-04-06 00:30:00  4fe0fd3f2130              daily snapshot    /source
6629478b  2021-04-07 00:30:00  4fe0fd3f2130              daily snapshot    /source
4214c6fe  2021-04-08 00:30:00  4fe0fd3f2130              daily snapshot    /source
14da0164  2021-04-09 00:30:00  4fe0fd3f2130              daily snapshot    /source
f6c00cff  2021-04-10 00:30:00  4fe0fd3f2130              daily snapshot    /source
                                                         weekly snapshot
                                                         monthly snapshot
----------------------------------------------------------------------------------
9 snapshots

keep 8 snapshots:
ID        Time                 Host          Tags        Reasons           Paths
----------------------------------------------------------------------------------
8d5bcc16  2021-03-14 00:30:00  a027cf32ab20              weekly snapshot   /source
bcee87f0  2021-03-20 00:30:00  a027cf32ab20              daily snapshot    /source
3bc37f2d  2021-03-21 00:30:00  a027cf32ab20              daily snapshot    /source
                                                         weekly snapshot
e011cc54  2021-03-22 00:30:00  a027cf32ab20              daily snapshot    /source
9ede7d97  2021-03-23 00:30:00  a027cf32ab20              daily snapshot    /source
748394fd  2021-03-24 00:30:00  a027cf32ab20              daily snapshot    /source
314e99cc  2021-03-25 00:30:00  a027cf32ab20              daily snapshot    /source
354bc17d  2021-03-26 00:30:00  a027cf32ab20              daily snapshot    /source
                                                         weekly snapshot
                                                         monthly snapshot
----------------------------------------------------------------------------------
8 snapshots

keep 7 snapshots:
ID        Time                 Host          Tags        Reasons           Paths
----------------------------------------------------------------------------------
76d9b3d3  2021-04-25 00:30:31  a9931d0bb0ea              daily snapshot    /source
                                                         weekly snapshot
742074f1  2021-04-26 00:30:30  a9931d0bb0ea              daily snapshot    /source
61839cf4  2021-04-27 00:30:31  a9931d0bb0ea              daily snapshot    /source
58039fb8  2021-04-28 00:30:30  a9931d0bb0ea              daily snapshot    /source
50bb69dc  2021-04-29 00:30:30  a9931d0bb0ea              daily snapshot    /source
64b09a39  2021-04-30 00:30:30  a9931d0bb0ea              daily snapshot    /source
                                                         monthly snapshot
7f0d3924  2021-05-01 00:30:31  a9931d0bb0ea              daily snapshot    /source
                                                         weekly snapshot
                                                         monthly snapshot
----------------------------------------------------------------------------------
7 snapshots
```

However, I am using only one repository, so I don't understand why I have several hosts.
The main problem is that the forget policies are therefore not respected.

Do you have any idea why such thing happens?
I suppose that a new host is created each time I restart the docker container, but not sure yet.

Here is my `docker-compose` section for resticker:
``` yaml
  restic:
    container_name: restic
    image: mazzolino/restic
    restart: unless-stopped
    networks:
      - t2_proxy
    environment:
      - BACKUP_CRON=0 30 0 * * *
      - RESTIC_REPOSITORY=b2:tdehaeze:/restic
      - RESTIC_PASSWORD=$RESTIC_PASSWORD
      - RESTIC_BACKUP_SOURCES=/source
      - RESTIC_FORGET_ARGS=--keep-daily 7 --keep-weekly 4 --keep-monthly 12
      - RESTIC_BACKUP_ARGS=--exclude-file /exclude.txt
      - B2_ACCOUNT_ID=$RESTIC_B2_ACCOUNT_ID
      - B2_ACCOUNT_KEY=$RESTIC_B2_ACCOUNT_KEY
      - UID=$PUID
      - GID=$PGID
      - TZ=$TZ
    volumes:
      - $CONFIGDIR/restic/exclude.txt:/exclude.txt:ro
      - /srv/storage/Cloud:/source/Cloud:ro
```

Thanks

**Comment by escoand** [comment]
@tdehaeze I experienced the same problem and use the hostname parameter and forget grouped by tag:

```yaml
backup:
    container_name: backup
    image: mazzolino/restic
    hostname: ${HOSTNAME}
    restart: unless-stopped
    cpu_percent: 50
    environment:
      - B2_ACCOUNT_ID
      - B2_ACCOUNT_KEY
      - BACKUP_CRON=0 0 2 * * *
      - POST_COMMANDS_FAILURE
      - POST_COMMANDS_SUCCESS
      - PRE_COMMANDS=
          docker exec mariadb mysqldump -A |
          gzip > /data/mariadb.sql.gz
      - RESTIC_BACKUP_ARGS=
          --exclude '*.log'
          --exclude 'appdata_*'
          --exclude 'files_trashbin'
          --exclude 'updater-*'
          --exclude-if-present '.nobackup'
          --exclude-if-present 'ibdata1'
          --exclude-if-present 'platformio.ini'
          --tag local
      - RESTIC_FORGET_ARGS=
          --group-by tag
          --keep-daily 7
          --keep-weekly 5
          --keep-monthly 12
          --prune
      - RESTIC_PASSWORD
      - RESTIC_REPOSITORY
      - TZ
    volumes:
      - ${DATA_DIR}:/data
      - /var/run/docker.sock:/var/run/docker.sock
```
