### ISSUE TITLE
Prune does not work when RESTIC_FORGET_ARGS is not set

### ISSUE THREAD

**Issue by MartinEnders** [djmaze/resticker#99]
Hi,

prune stopped working in my configuration after the introduction of RESTIC_FORGET_ARGS parameter in commit fcde625d0b9548ae5e138c0126269074d525407a

I do not set `RESTIC_FORGET_ARGS` in my docker-compose file which produces the following error:
```
/usr/local/bin/prune: line 20: RESTIC_FORGET_ARGS: unbound variable
```
Remark: When the error occurs the `POST_COMMAND_FAILURE` is not executed.

I use an extra container for prune, therefore I set the RESTIC_FORGET_ARGS already for the backup containers.

I think the problem is located in the following line: 

https://github.com/djmaze/resticker/blob/b88b7f92e4a32eeccb84f69d5386535289f219cd/prune#L20 

DISCLAIMER: I do not have much experience in bash programming.

I think the current solution needs the `RESTIC_FORGET_ARGS` variable set (to empty value) instead of checking if the variable is set at all.

According to the following stackoverflow answer (https://stackoverflow.com/a/13864829) it might be more intuitive for the users to use `-z` to test if the variable is set.

Here is my configuration from my docker-compose file for the prune container (I use an extra container only for prune) with the RESTIC_FORGET_ARGS set to empty string `""` as workaround to make prune working.

The described error occours if the line with `RESTIC_FORGET_ARGS` is removed.

```
  prune:
    image: mazzolino/restic
    hostname: docker
    container_name: prune
    restart: unless-stopped
    environment:
      RUN_ON_STARTUP: "false"
      PRUNE_CRON: "0 0 4 * * 1"
      RESTIC_REPOSITORY: b2:xxxx
      RESTIC_PASSWORD: xxxx
      B2_ACCOUNT_ID: xxxx
      B2_ACCOUNT_KEY: xxxx
      RESTIC_FORGET_ARGS: ""
      TZ: Europe/Berlin
      PRE_COMMANDS: |-
         curl -s -S --no-progress-meter -X POST --data "{\"title\": \"Prune Starting\", \"body\": \"\"}" http://xxxx:5000
      POST_COMMANDS_SUCCESS: |-
         curl -s -S --no-progress-meter -X POST --data "{\"title\": \"Prune successful\", \"body\": \"\"}" http://xxxx:5000
      POST_COMMANDS_FAILURE: |-
         curl -s -S --no-progress-meter -X POST --data "{\"title\": \"Prune failed\", \"body\": \"\"}" http://xxxx:5000
      POST_COMMANDS_EXIT: |-
         curl -s -S --no-progress-meter -X POST --data "{\"title\": \"Prune END\", \"body\": \"\"}" http://xxxx:5000
    networks:
      - notification
```

Best regards
Martin

PS: Thank you for providing this fantastic docker images for backups :-)
